#!/usr/bin/env python3
"""Read-pack generator for section 7: every hop of every Yen's route, with every
receipt's full passage text, for hand reading.

Run:  NEO4J_DATABASE=lewisclark .venv/bin/python scripts/make_paths_readpack.py
Writes results/paths-lewisclark-readpack.md
"""
from __future__ import annotations

import sys
from pathlib import Path as FsPath

sys.path.insert(0, str(FsPath(__file__).resolve().parents[1] / "scripts"))
import _bootstrap  # noqa: F401

from graphrank import paths
from graphrank.config import query
from graphrank.paths import PathConfig
from graphrank.resolve import resolve_entity

PAIRS = [
    ("Sacagawea", "Shoshone"),
    ("Sacagawea", "Cameahwait"),
    ("Toussaint Charbonneau", "Hidatsa"),
    ("Grizzly Bear", "Great Falls"),
]

OUT = FsPath(__file__).resolve().parent / "paths-lewisclark-readpack.md"


def chunk_text(chunk_id: str) -> dict | None:
    rows = query(
        """
        MATCH (c:Chunk {chunkId: $id})
        RETURN c.chunkId AS chunkId, c.text AS text,
               toString(c.date) AS date, c.author AS author
        """,
        id=chunk_id,
    )
    return rows[0] if rows else None


def all_rels_between(a_name: str, b_name: str) -> list[dict]:
    """Every stored relationship between two named entities, with raw props."""
    return query(
        """
        MATCH (a)-[r]-(b)
        WHERE coalesce(a.canonicalName, a.name) = $aName
          AND coalesce(b.canonicalName, b.name) = $bName
          AND type(r) <> 'MENTIONED_IN'
        WITH DISTINCT r,
             coalesce(startNode(r).canonicalName, startNode(r).name) AS fromN,
             coalesce(endNode(r).canonicalName, endNode(r).name)     AS toN
        RETURN fromN, type(r) AS relType, toN,
               CASE WHEN valueType(r.chunkId) STARTS WITH 'LIST'
                    THEN r.chunkId ELSE [r.chunkId] END AS chunkIds,
               CASE WHEN valueType(r.date) STARTS WITH 'LIST'
                    THEN [d IN r.date | toString(d)]
                    ELSE [toString(r.date)] END          AS dates,
               valueType(r.chunkId) STARTS WITH 'LIST'   AS isList
        """,
        aName=a_name,
        bName=b_name,
    )


def main() -> int:
    lines: list[str] = ["# Section 7 read-pack — Yen's routes on `lewisclark`", ""]
    lines.append("Generated by `make_paths_readpack.py`. One block per anchor pair; "
                 "every hop lists ALL stored relationships between its endpoints "
                 "(the hydrator shows only the earliest-dated one), and every "
                 "receipt's full passage text.")
    seen_chunks: set[str] = set()

    for src_name, dst_name in PAIRS:
        src = resolve_entity(src_name)
        dst = resolve_entity(dst_name)
        lines.append(f"\n\n## {src_name} → {dst_name}")
        if not src or not dst:
            lines.append(f"UNRESOLVED: {src_name if not src else dst_name}")
            continue
        lines.append(f"resolved: {src.name} ({src.label}, {src.mentions} mentions, "
                     f"{src.resolved_via}) → {dst.name} ({dst.label}, "
                     f"{dst.mentions} mentions, {dst.resolved_via})")

        found = paths.k_shortest_paths(src, dst, config=PathConfig(k_paths=8, max_hops=5))
        lines.append(f"routes returned: {len(found)}")

        for ri, path in enumerate(found, 1):
            lines.append(f"\n### Route {ri} ({path.hops} hops, cost {path.total_cost:g})")
            lines.append("`" + " -> ".join(f"{n.name} ({n.label})" for n in path.nodes) + "`")
            for hi, rel in enumerate(path.relationships, 1):
                lines.append(f"\n#### Hop {hi}: {rel.from_name} -[{rel.rel_type}]-> "
                             f"{rel.to_name}  (hydrator shows: {rel.chunk_id or 'structural'}"
                             f" · {rel.date or 'undated'})")
                stored = all_rels_between(rel.from_name, rel.to_name)
                for s in stored:
                    tag = " **LIST**" if s["isList"] else ""
                    lines.append(f"- stored: `({s['fromN']}) -[{s['relType']}]-> ({s['toN']})`"
                                 f"{tag} receipts: {len([c for c in s['chunkIds'] if c])}")
                    for cid, d in zip(s["chunkIds"], s["dates"]):
                        if cid is None:
                            lines.append("    - (no chunkId — structural)")
                            continue
                        marker = " ◀ hydrator's pick" if cid == rel.chunk_id else ""
                        lines.append(f"    - `{cid}` · {d}{marker}")
                        if cid not in seen_chunks:
                            seen_chunks.add(cid)
                            c = chunk_text(cid)
                            if c:
                                text = " ".join(c["text"].split())
                                lines.append(f"      > **{c['author']} · {c['date']}**: {text}")
                            else:
                                lines.append("      > CHUNK NOT FOUND")
                        else:
                            lines.append("      > (passage shown earlier)")

        # what evidence_chunks() would hand the LLM
        ev = paths.evidence_chunks(found, limit=8)
        lines.append(f"\n### evidence_chunks() output ({len(ev)} passages)")
        for c in ev:
            lines.append(f"- `{c.chunk_id}` · {c.author} · {c.date} · source={c.source}")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines, {len(seen_chunks)} distinct chunks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
